"""
PDF Report Module
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet


class PDFExporter:

    @staticmethod
    def export(expenses):

        # Create exports folder
        os.makedirs("exports", exist_ok=True)

        filename = datetime.now().strftime(
            "exports/Expense_Report_%Y%m%d_%H%M%S.pdf"
        )

        document = SimpleDocTemplate(
            filename,
            pagesize=A4
        )

        styles = getSampleStyleSheet()

        elements = []

        # ---------------- Title ---------------- #

        elements.append(
            Paragraph(
                "<b><font size=20>Expense Tracker Pro</font></b>",
                styles["Title"]
            )
        )

        elements.append(
            Paragraph(
                "<b>Expense Report</b>",
                styles["Heading2"]
            )
        )

        elements.append(
            Paragraph(
                f"Generated On : {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
                styles["Normal"]
            )
        )

        elements.append(Spacer(1, 20))

        # ---------------- Table ---------------- #

        table_data = [
            [
                "ID",
                "Title",
                "Category",
                "Amount",
                "Date",
                "Note"
            ]
        ]

        total_amount = 0

        for expense in expenses:

            total_amount += expense[3]

            table_data.append([
                expense[0],
                expense[1],
                expense[2],
                f"₹ {expense[3]:.2f}",
                expense[4],
                expense[5]
            ])

        table = Table(table_data)

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0,0), (-1,0), colors.darkblue),

                ("TEXTCOLOR", (0,0), (-1,0), colors.white),

                ("ALIGN", (0,0), (-1,-1), "CENTER"),

                ("GRID", (0,0), (-1,-1), 1, colors.black),

                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0,0), (-1,0), 10),

                ("BACKGROUND", (0,1), (-1,-1), colors.beige)

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 20))

        # ---------------- Summary ---------------- #

        elements.append(

            Paragraph(

                f"<b>Total Records :</b> {len(expenses)}",

                styles["Heading3"]

            )

        )

        elements.append(

            Paragraph(

                f"<b>Total Expense :</b> ₹ {total_amount:.2f}",

                styles["Heading3"]

            )

        )

        elements.append(Spacer(1, 25))

        elements.append(

            Paragraph(

                "<b>Generated by Expense Tracker Pro</b>",

                styles["Normal"]

            )

        )

        document.build(elements)

        return filename